/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    id("org.springframework.boot") version "3.5.3"
}

apply(plugin = "io.spring.dependency-management")

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation(libs.org.springframework.boot.spring.boot.starter)
    implementation(libs.org.springframework.boot.spring.boot.starter.web)
    implementation(libs.org.apache.pdfbox.pdfbox)
    implementation(libs.net.sourceforge.tess4j.tess4j)
    implementation(libs.com.fasterxml.jackson.core)
    implementation(libs.software.amazon.awssdk.s3)
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
}

group = "com.nassiesse.ocr"
version = "0.0.1-SNAPSHOT"
description = "SimpleOCRMicroservice"
java.sourceCompatibility = JavaVersion.VERSION_21
java.targetCompatibility = JavaVersion.VERSION_21

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<Test> {
    useJUnitPlatform();
}

tasks.named<org.springframework.boot.gradle.tasks.run.BootRun>("bootRun") {
    mainClass.set("com.nassiesse.ocr.SimpleOcrMicroserviceApplication")
}

/*
tasks.withType<Jar> {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
    exclude("META-INF/*.SF", "META-INF/*.DSA", "META-INF/*.RSA")
    from(configurations.runtimeClasspath.get().map {
        if (it.isDirectory) it else zipTree(it)
    })
}*/

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc> {
    options.encoding = "UTF-8"
}
