services:
  api:
    restart: always
    build:
      context: ./
    expose:
      - 8082
    environment:
      JAVA_OPTS: "-Dfile.encoding=UTF8 -Dspring.profiles.active=dev -Xmx2048m -Xmx2048m"
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
    ports:
      - "8082:8082"